site_name: ComboGenius Documentation

nav:
  - Home: index.md
  - API: API.md
  - Database: Database.md
  - Models: Models.md

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]

theme: readthedocs